# Generated by Django 5.1.3 on 2025-02-07 17:18

import Teleapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('phones', 'Phones'), ('tablets', 'Tablets'), ('laptops', 'Laptops'), ('accessories', 'Accessories'), ('headphones', 'Headphones'), ('watches', 'Watches')], max_length=50, verbose_name='Категория')),
                ('obj_id', models.AutoField(primary_key=True, serialize=False, verbose_name='уникальный id товара')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Изображение карточки товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('specs', models.JSONField(default=Teleapp.models.default_specs, verbose_name='Характеристики')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Базовый товар',
                'verbose_name_plural': 'Базовые товары',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['title'], name='Teleapp_pro_title_2668fd_idx'), models.Index(fields=['-created'], name='Teleapp_pro_created_e40051_idx'), models.Index(fields=['category'], name='Teleapp_pro_categor_3373a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50, verbose_name='title')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='Teleapp.product')),
            ],
            options={
                'verbose_name': 'Параметры товара',
                'verbose_name_plural': 'Параметры товара',
            },
        ),
        migrations.CreateModel(
            name='IMAGE_PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Характеристика')),
                ('image', models.ImageField(upload_to=Teleapp.models.get_variant_image_upload_path, verbose_name='Изображение Продукта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Teleapp.variantimage')),
            ],
            options={
                'verbose_name': 'для конкретного характеристики Модели',
                'verbose_name_plural': 'для конкретного характеристики Модели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumbler1', models.CharField(max_length=50, verbose_name='tumbler1')),
                ('tumbler2', models.CharField(blank=True, max_length=50, null=True, verbose_name='tumbler2')),
                ('tumbler3', models.CharField(blank=True, max_length=50, null=True, verbose_name='tumbler3')),
                ('tumbler4', models.CharField(blank=True, max_length=50, null=True, verbose_name='tumbler4')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество в наличии')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='Teleapp.variantimage')),
            ],
            options={
                'verbose_name': 'Тумблеры товара',
                'verbose_name_plural': 'Тумблеры товара',
                'unique_together': {('base_product', 'tumbler1', 'tumbler2', 'tumbler3', 'tumbler4')},
            },
        ),
    ]
