# Generated by Django 5.1.3 on 2025-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
