# Generated by Django 5.1.3 on 2025-02-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0002_variantimage_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimage',
            name='sort_order',
        ),
    ]
