# Generated by Django 5.1.3 on 2025-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0003_remove_variantimage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок'),
        ),
    ]
