# Generated by Django 5.1.3 on 2025-02-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0005_remove_variantimage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='default_obj',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/%Y/%m/%d', verbose_name='Изображение карточки товара'),
        ),
    ]
