# Generated by Django 5.1.3 on 2025-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0006_variantimage_default_obj_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='уникальный id товара'),
        ),
    ]
