# Generated by Django 5.1.3 on 2025-03-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0007_alter_variantimage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('variants', models.ManyToManyField(related_name='recommendation_blocks', to='Teleapp.variantimage', verbose_name='Варианты товаров')),
            ],
            options={
                'verbose_name': 'Блок рекомендаций',
                'verbose_name_plural': 'Блоки рекомендаций',
                'ordering': ['order'],
            },
        ),
    ]
