# Generated by Django 5.1.3 on 2025-03-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0008_recommendationblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationblock',
            name='catalog_description',
            field=models.CharField(default='Описание по умолчанию', max_length=100, verbose_name='Описание блока'),
        ),
        migrations.AlterField(
            model_name='recommendationblock',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название блока'),
        ),
    ]
