# Generated by Django 5.1.3 on 2025-03-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teleapp', '0009_recommendationblock_catalog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Укажите уникальный порядок отображения блока.', unique=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='recommendationblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название блока'),
        ),
    ]
